name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type checking
      run: npm run type-check
    
    - name: Run tests
      run: npm run test:ci
    
    - name: Build package
      run: npm run build:prod
    
    - name: Check package size
      run: |
        npm run size-check
        echo "Package size details:"
        npm run size-check:detail
    
    - name: Test global installation
      run: |
        npm run pack:test
        # Test that the binary works after global install
        npm install -g ./mac-chrome-cli-*.tgz
        which mac-chrome-cli
        mac-chrome-cli --version
        mac-chrome-cli test
        npm uninstall -g mac-chrome-cli
    
    - name: Upload coverage to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting (placeholder)
      run: npm run lint

  package-validation:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate package.json
      run: npm run validate
    
    - name: Test pack (dry run)
      run: npm run pack:dry
    
    - name: Check files included in package
      run: |
        echo "Files that will be included in the npm package:"
        npm pack --dry-run | grep -E "^\s*[0-9]+\s+[0-9]+" | head -20
        echo "..."
        echo "Total files: $(npm pack --dry-run | grep -E "^\s*[0-9]+\s+[0-9]+" | wc -l)"
    
    - name: Verify dist directory
      run: |
        ls -la dist/
        echo "Checking that binary has correct shebang:"
        head -1 dist/index.js
        echo "Checking that binary is executable:"
        test -x dist/index.js && echo "✅ Executable" || echo "❌ Not executable"